name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Запускать workflow только при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install docker compose
      run: |
        sudo curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Шаг 3: Сборка приложения в Docker
    - name: Run Docker Compose
      run: docker-compose up -d --build