name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Запускать workflow только при пуше в ветку main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода
    - name: Checkout repository
      uses: actions/checkout@v3

    # Шаг 2: Установка Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*\d')" /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Шаг 3: Сборка приложения в Docker
    - name: Build application
      run: docker-compose up -d --build

    # Шаг 5: Деплой на GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Папка со статическими файлами
        publish_branch: gh-pages  # Ветка для GitHub Pages